# Generated by Django 4.1.6 on 2023-06-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaNoticias',
            fields=[
                ('idArea', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='codigo')),
                ('autor', models.CharField(max_length=50, verbose_name='autor')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('Contenido', models.CharField(max_length=255, verbose_name='Contenido')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='img')),
                ('idArea', models.ForeignKey(db_column='idArea', on_delete=django.db.models.deletion.CASCADE, to='aplicacion.areanoticias', verbose_name='idArea')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
