# Generated by Django 4.2.1 on 2023-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Contenido')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/aut/', verbose_name='img')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='noticias',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/', verbose_name='img'),
        ),
    ]
