# Generated by Django 4.2.1 on 2023-07-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='Contenido',
            field=models.TextField(max_length=255, verbose_name='Contenido'),
        ),
    ]
